export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const ASSISTANT_USER_REQUEST = "ASSISTANT_USER_REQUEST";
export const ASSISTANT_USER_SUCCESS = "ASSISTANT_USER_SUCCESS";
export const ASSISTANT_USER_FAIL = "ASSISTANT_USER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS"